
GET http://localhost:8888/catagory

###

GET  http://localhost:8888/catagory/64434cdd357b196957613422

###

POST http://localhost:8888/catagory
Content-Type: application/json

{
    "name": "Catagory 2",
    "color": "#333",
    "icon": "Icon Catagory 2"
}

###

DELETE http://localhost:8888/catagory/6442c1b265c8ef367c57deb6

###

PUT http://localhost:8888/catagory/64434cdd357b19695761342
Content-Type: application/json

{
    "name": "Catagory 2 - updated",
    "color": "#222",
    "icon": "Icon Catagory 2 - updated"
}


###


POST http://localhost:8888/products
Content-Type: application/json

{
    "name": "Product 2",
    "description": "Description Product 2",
    "richDescription": "Rich Description Product 2",
    "image": "Image Product 2",
    "brand": "Brand 2",
    "price": 20,
    "catagory": "6443690e0029d49d612941c",
    "countInStock": 6,
    "rating": 8,
    "numReviews": 3,
    "isFeatured": false
}

###

GET http://localhost:8888/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6eyJ1c2VySW5mbyI6IjY0NDg3YTg5OGQwMGQxMDU1MmViMmQ3YyIsImlhdCI6MTY4MjQ5NzA3NywiZXhwIjoxNjgyNTgzNDc3fSwiaWF0IjoxNjgyNDk3MDk1LCJleHAiOjE2ODI0OTcxMTB9.W-XINENxnqrJCOEZt5Vn-nmCYPrI3Ywzrb4CrDY8Wq4
###

GET http://localhost:8888/products/64455388c5554f9eb7b66165

###

PUT http://localhost:8888/products/64455388c5554f9eb7b66165

###

POST http://localhost:8888/users/register
Content-Type: application/json

{
    "name": "Van Manh",
    "email": "vanmanh@email.com",
    "password": "1234",
    "phone": "9765900727",
    "isAdmin": true,
    "apartment": "Apartment 202",
    "zip": "10000",
    "city": "Thon Trung",
    "country": "Viet Nam"
}

###

GET http://localhost:8888/users

###

POST http://localhost:8888/users/login
Content-Type: application/json

{
    "email": "vanmanh@email.com",
    "password" : "1234"
}

###
POST http://localhost:8888/users/token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mbyI6IjY0NDg3YTg5OGQwMGQxMDU1MmViMmQ3YyIsImlhdCI6MTY4MjQ5NzA3NywiZXhwIjoxNjgyNTgzNDc3fQ.LSkjGrwGGwKxundpK9p-kixP89OqqU62IifdHMbOePc"
}